use_frameworks!

platform :ios, '8.0'

target 'CDTitleSlideWrapView_Example' do
  pod 'CDTitleSlideWrapView', :path => '../'
  pod 'Masonry', '~> 1.1.0'
  target 'CDTitleSlideWrapView_Tests' do
    inherit! :search_paths

    
  end
end
